### PR TITLE
Cw/improve docs search

### PR DESCRIPTION
**Pull request by ChrisWeissmann**
# Issue #165 

## Description

- Added the aligola integration to the project. 

## Screenshot
Bildschirmfoto 2019-05-24 um 13 03 43

### CODE REVIEW

**Comment by adrianjost** [comment]
Is it okay to have this apikey publicly exposed or should we use an env variable instead?

**Comment by ChrisWeissmann** [comment]
> Is it okay to have this apikey publicly exposed or should we use an env variable instead?

Very good point! I will change it

**Comment by adrianjost** [comment]
Please also add the new variables to the docs: https://github.com/schul-cloud/nuxt-client/blob/cw/Improve-Docs-Search/docs/0-GettingStarted/1-Build.md
I would prefer to create a second table for each subproject to make it clear, which variable is required for which build.

**Comment by adrianjost** [comment]
@ChrisWeissmann FIY: I removed your commits from history by force pushing over it to remove the key from the git history. It's still available with some tricks, but should be fine for now.

**Pull request merged**
