### PR TITLE
add surge deployments to all pull requests

### PR DESCRIPTION
**Pull request by adrianjost**
## ~⚠ **TODO:**~ **✅ DONE**
1. ~We should replace all access tokens in travis with schul-cloud specific ones. Currently I am using my own ones.~
2. ~We should get a [premium surge.sh account for 30$/month](https://surge.sh/pricing) to have unlimited deployment urls~ Not needed 
image

3. ~We need a GITHUB_TOKEN for the schul-cloud organization. I think we need to create a new github user for that. I would go for a generic name like "schul-cloud-bot" or similar.~ **DONE:** https://github.com/schul-cloud-bot

### Required Travis Env Variables:
- [x] `SURGE_LOGIN`
- [x] `SURGE_TOKEN`
- [x] `GITHUB_TOKEN` with the following access rights 
image

## Description

- Discussed as an Idea with @dominikbruechner to improve the workflow by providing a deployment per pull request to improve communication with non devs.
- Every Pull will be pushed to https://surge.sh which offers free hosting and we can choose whatever domain we need. Before actively using it, we should check that we are for sure not breaking any license by using it in this environment.

Workflow:
1. Travis Builds our pulls like it did before
1. If the Branch is a Pull and is not the master branch (maybe redundant but hey, better be safe). If it is, it deploys the storybook and docs build to surge.sh to the following domains:
    1. **Docs:** https://docs.${TRAVIS_PULL_REQUEST}.nuxt.schul-cloud.surge.sh
    1. **Storybook:** https://stories.${TRAVIS_PULL_REQUEST}.nuxt.schul-cloud.surge.sh
After a successfull deploy, it is also posting a comment to the pull request with the used urls using the github api.

Currently Deployed Pulls will never get teared down. We maybe need to improve this later on. Maybe it's possible by running a custom shell script on travis build on the master branch.

### CODE REVIEW

**Comment by adrianjost** [comment]
Hi from the command line

**Comment by adrianjost** [comment]
Hi from the command line
with new
line

**Comment by adrianjost** [comment]
We deployed this pull-request for you. Check it out:

**Docs:** docs..nuxt.schul-cloud.surge.sh 
**Storybook:** stories..nuxt.schul-cloud.surge.sh

**Comment by adrianjost** [comment]
We deployed this pull-request for you. Check it out:

**Docs:** docs..nuxt.schul-cloud.surge.sh 
**Storybook:** https://stories..nuxt.schul-cloud.surge.sh

**Comment by adrianjost** [comment]
We deployed this pull-request for you. Check it out:

**Docs:** docs..nuxt.schul-cloud.surge.sh 
**Storybook:** https://stories..nuxt.schul-cloud.surge.sh

**Comment by adrianjost** [comment]
We deployed this pull-request for you. Check it out:

**Docs:** https://docs.191.nuxt.schul-cloud.surge.sh 
**Storybook:** https://stories.191.nuxt.schul-cloud.surge.sh

**Comment by adrianjost** [comment]
We deployed this pull-request for you. Check it out:

**Docs:** https://docs.191.nuxt.schul-cloud.surge.sh 
**Storybook:** https://stories.191.nuxt.schul-cloud.surge.sh

**Comment by adrianjost** [comment]
We deployed this pull-request for you. Check it out:

**Docs:** https://docs.191.nuxt.schul-cloud.surge.sh 
**Storybook:** https://stories.191.nuxt.schul-cloud.surge.sh

**Comment by adrianjost** [comment]
We deployed this pull-request for you. Check it out:

**Docs:** https://docs.191.nuxt.schul-cloud.surge.sh 
**Storybook:** https://stories.191.nuxt.schul-cloud.surge.sh

**Comment by adrianjost** [comment]
We deployed this pull-request for you. Check it out:

**Docs:** http://docs.191.nuxt.schul-cloud.surge.sh 
**Storybook:** http://stories.191.nuxt.schul-cloud.surge.sh

**Comment by ChrisWeissmann** [comment]
I was wondering if we will only deploy docs and storybook for the surge deployments?
Can we make a git action that tears down the site when the branch is deleted?

**Comment by adrianjost** [comment]
@ChrisWeissmann We can't deploy the nuxt client itself with this method, because it will be not static anymore and surge only supports static file webhosting. We would need a docker base solution for that like I posted it in the dev channel: https://thecode.pub/creating-review-apps-per-pull-requests-c8c9dfa02ffb
The reason is the new fallback for the old client that needs to be server side rendered.

I already thought about teardown old deployments but haven't found an easy solution yet. Surge.sh offers unlimited domains & projects so it's not that big of a deal and I will take a look on this later, when we have some deployments. It's pretty hard to code something for a tool that isn't fully setup yet ^^

**Comment by adrianjost** [comment]
@dominikbruechner All Accounts are now created and the travis tokens are updated. We can merge this now 🍾

**Comment by adrianjost** [comment]
> had a thought, will google & co index our site on the internet? Is that maybe not so good in spamming search results with old branches etc

Good point. We could simply add a robots.txt to all out deployments. I will add this in another branch

**Pull request merged**
