### PR TITLE
SC-5486 - fixing broken font scaling in nuxt

### PR DESCRIPTION
**Pull request by dominikbruechner**
reordering the imports fixes font scaling problem in nuxt

Ticket Reference: https://ticketsystem.schul-cloud.org/browse/SC-5486

==> Implications:
check every new page and component, as the font sizes propagate through everything
- Admin
- Datasources
- Content

### CODE REVIEW

**Comment by dominikbruechner** [comment]
@schul-cloud-bot update screenshots

**Comment by CeEv** [comment]
@dominikbruechner approved but many merge conflicts.

**Comment by BlackGhostHD** [comment]
Sorry, I only just got a chance to check it out. So far I can only see two small problems
Opera Momentaufnahme_2020-07-14_103614_localhost
Anmerkung 2020-07-14 103737

**Comment by BlackGhostHD** [comment]
@schul-cloud-bot update screenshots

**Comment by BlackGhostHD** [comment]
Couldn't find any other UI errors using Sizzy

**Pull request merged**
