### PR TITLE
#104 design system

### PR DESCRIPTION
**Pull request by adrianjost**
# Issue #104 

**I know, this pull is really large. Sorry for that!**

## Description

I mostly followed this _"guide"_: https://medium.com/codyhouse/create-your-design-system-part-1-typography-7c630d9092bd

- instead of using sass variables, I coverted everything to css custom properties (`var(--...)`)
- I refactored all variable names and fonts
- All Style Variables & Helper Classes can be checked out using vuepress ( http://localhost:4002/2-Styles/0-Variables.html )

**We should definetly discuss** which of the helper classes we really wan't and what variables are missing, badly named, ....

## Screenshot

Die Screenshots sind nicht mehr ganz aktuell, aber grundsätzlich ist das Konzept gleich geblieben. Die Variablen wurden nur nach Absprache mit Domi weiter vereinfacht.

### Variables (outdated)
localhost_4002_2-Styles_0-Variables html(iPad)
localhost_4002_2-Styles_1-UtilityClasses html(iPad)

### CODE REVIEW

**Comment by dominikbruechner** [comment]
I am going look on it more in detail soon, but first @ChrisWeissmann , does the headline variable part interfere with your scaling headline approach? and therefore, do we need specified sizes for the headlines?

**Comment by dominikbruechner** [comment]
about colors variables and all the shades: I would wish to restrict the color variables to only a few, pre-defined by the visual designer AKA mona. particularly, the tonal palette for gray will eventually lead to non-consistent use of those colors in the interface. Better go with fewer for now and add some colors on the way if they are missing, instead of having inconsistent use in the end

**Comment by adrianjost** [comment]
> about colors variables and all the shades: I would wish to restrict the color variables to only a few, pre-defined by the visual designer AKA mona. particularly, the tonal palette for gray will eventually lead to non-consistent use of those colors in the interface. Better go with fewer for now and add some colors on the way if they are missing, instead of having inconsistent use in the end

I totally agree. Fewer variables are better! I had removing some of those already on my todolist. At the moment I just finished copiing and setting up everything from the tutorial. That's also the reason why I haven't assigned anyone yet.But we will discuss this in more detail this thursday :)

**Comment by adrianjost** [comment]
@ChrisWeissmann überprüft nochmal meine Änderungen an der CourseCard

Rücksprache mit Mona zu den Typo Sachen findet gleich statt.

**Comment by dominikbruechner** [comment]
what's the status here? Mona is today and tomorrow in the office with me

**Comment by dominikbruechner** [comment]
You were overwriting changes on the button component of @ChrisWeissmann 
I am resolving this in https://github.com/schul-cloud/nuxt-client/pull/189

**Comment by adrianjost** [comment]
@dominikbruechner I have written a message to mona asking for a timeslot to discuss the open questions (mostly typography and a bit spacing) but haven't got a response yet. I will come around tommorrow and try it spontaneous and hopefully can resolve all open questions. I will tell you as soon as it is finished. I hope this will be done due friday.

& thanks for resolving 💯

**Comment by adrianjost** [comment]
closing in favor of #190

**Pull request closed without merging**
