### PR TITLE
SC-5480 - fixed selection population bug

### PR DESCRIPTION
**Pull request by BlackGhostHD**
# Description

## Links to Tickets or other pull requests

https://ticketsystem.schul-cloud.org/browse/SC-5480

## Screenshots of UI changes
Sizzy-iPhone 11 Pro localhost 13Jul 14 12
Sizzy-iPhone 11 Pro localhost 13Jul 14 12-1
Sizzy-iPhone 11 Pro localhost 13Jul 14 12-2

## Approval for review

- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

### CODE REVIEW

**Comment by BlackGhostHD** [comment]
@ABialoskorski The selection for the topics is empty if no course is selected. Should the field be disabled completely if no course is selected?

**Comment by mwolowyk-cap** [comment]
@BlackGhostHD  What if the course has no topics? Should we show the warning? Should it be handled in this PR?

**Comment by BlackGhostHD** [comment]
@mwolowyk-cap Is already implemented with this PR, but I couldn't test it sufficiently yesterday, if everything works. Will do that on Monday

**Comment by BlackGhostHD** [comment]
@schul-cloud-bot update screenshots

**Pull request merged**
