### PR TITLE
add news create & edit page

### PR DESCRIPTION
**Pull request by adrianjost**
# Issue: [Vue-22](https://ticketsystem.schul-cloud.org/browse/VUE-22) & [VUE-149](https://ticketsystem.schul-cloud.org/browse/VUE-149)

## Open TODOs

- [x] add more tests to not drop the coverage
- [x] add cancel modal to confirm loosing changes
  - [x] depends on #376
- [x] ~use top right FAB as edit button~ has nothing to do with these pages. Should be implemented in another branch/pull

## Description

- cherrypick from #301 
- implemented news edit and create page
- other changes will be done in seperate pull requests (input style adjustments, ...)

## Related Pulls
- https://github.com/schul-cloud/integration-tests/pull/39

## Screenshot

image
image

### CODE REVIEW

**Comment by adrianjost** [comment]
Integration-Test Adjustments missing

**Comment by dominikbruechner** [comment]
suggestion: Add a new layout (centered?, similar to what we've had, with max-width xxx) which shows the form not in the full screen-width on desktop devices

**Comment by adrianjost** [comment]
@dominikbruechner that already the case. We center by default. But I will open another pull soon where I have implmeneted a full width layout that we can use for overview pages

**Comment by dominikbruechner** [comment]
> @dominikbruechner that already the case. We center by default. But I will open another pull soon where I have implmeneted a full width layout that we can use for overview pages

Ah I was not communicating it properly. I was targeting on the max-width, as pages like e.g. the form, or the impressum are stretching over the full screen width right now. 

Once we scale the fonts again according to the viewports, it will be nicer anyway I guess

**Comment by adrianjost** [comment]
> > @dominikbruechner that already the case. We center by default. But I will open another pull soon where I have implmeneted a full width layout that we can use for overview pages
> 
> Ah I was not communicating it properly. I was targeting on the max-width, as pages like e.g. the form, or the impressum are stretching over the full screen width right now.
> 
> Once we scale the fonts again according to the viewports, it will be nicer anyway I guess

I guess understood you, but the default  layout currenlty doesn have a max-width so it does not span across the full page.

**Comment by dominikbruechner** [comment]
Screen Shot 2019-11-26 at 11 56 37
(Safari, glitch)

**Comment by dominikbruechner** [comment]
Screen Shot 2019-11-26 at 12 13 09

News --> Neuigkeiten

**Comment by adrianjost** [comment]
> Screen Shot 2019-11-26 at 11 56 37
> (Safari, glitch)

Fixe ich hiermit:
https://github.com/schul-cloud/nuxt-client/pull/375

**Comment by adrianjost** [comment]
> Screen Shot 2019-11-26 at 12 13 09
> 
> News --> Neuigkeiten

Hab das auf die language files umgestellt. Hatte ich wohl übersehen.

**Comment by dominikbruechner** [comment]
great thanks!

regarding the delete modal: please check the storybook modal here https://storybook.test.schul-cloud.org/?path=/story/base-modals--dialog 
that's the layout we always want to use for delete confirmations

**Comment by dominikbruechner** [comment]
> great thanks!
> 
> regarding the delete modal: please check the storybook modal here https://storybook.test.schul-cloud.org/?path=/story/base-modals--dialog
> that's the layout we always want to use for delete confirmations

we need the same modal for the "cancel" action,...

**Comment by dominikbruechner** [comment]
@adrianjost We need to remove the editor picture function till we do the news images properly (konsti requirement)

**Pull request merged**
