### PR TITLE
Simple FAB button

### PR DESCRIPTION
**Pull request by dominikbruechner**
# Issue: [Vue-140](https://ticketsystem.schul-cloud.org/browse/VUE-140)

## Description

- Adding a simple fab button
- icon changeable
- position changeable 
- storybook cleanup

## Screenshot

Screen Shot 2019-11-14 at 11 30 55

### CODE REVIEW

**Comment by janrenz** [comment]
A responsive Version would be nice (like the little version here https://material.io/components/buttons-floating-action-button/)

**Comment by dominikbruechner** [comment]
> A responsive Version would be nice (like the little version here https://material.io/components/buttons-floating-action-button/)

what exactly do you mean?

**Comment by janrenz** [comment]
the material one has a smaller version, that could automatically be used on smaller devices ..

**Comment by dominikbruechner** [comment]
> the material one has a smaller version, that could automatically be used on smaller devices ..

material uses the mini one for different kinds of action:
Screen Shot 2019-11-15 at 15 54 52

But we need a second size, true

**Comment by adrianjost** [comment]
@dominikbruechner as it's already merged, could we still discuss my open issues and maybe change them in a follow up PR?

**Pull request merged**
